<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Inertia\Inertia;
use Inertia\Response;

class ActivityController extends Controller
{
    public function index(): Response
    {
        return Inertia::render('Admin/Activities/Index', [
            'activities' => [
                [
                    'id' => 1,
                    'name' => 'River Rafting',
                    'slug' => 'river-rafting',
                    'short_description' => 'White-water rafting with certified guides.',
                    'full_description' => 'Enjoy thrilling rapids with full safety briefing and river-side refreshments.',
                    'category' => 'Water',
                    'location' => 'Rishikesh',
                    'destination' => 'Rishikesh',
                    'price_min' => 800,
                    'price_max' => 3000,
                    'price_type' => 'Per Person',
                    'duration' => '3 Hours',
                    'difficulty' => 'Moderate',
                    'status' => 'Active',
                    'featured' => true,
                    'packages_linked' => ['Rishikesh Adventure Blast', 'Weekend River Escape'],
                    'image' => 'https://images.unsplash.com/photo-1521334884684-d80222895322?auto=format&fit=crop&w=1200&q=80',
                    'gallery' => [],
                    'tags' => ['Water Sports', 'Group'],
                    'age_limit' => '14+',
                    'best_time' => 'Sep to Jun',
                    'safety_instructions' => 'Life jacket mandatory. Follow instructor commands.',
                    'included' => 'Guide, raft gear, locker',
                    'excluded' => 'Personal insurance, transport',
                    'seo_title' => 'River Rafting Activity',
                    'meta_description' => 'Premium rafting activity for adventure tours.',
                    'keywords' => 'rafting,rishikesh,adventure',
                ],
                [
                    'id' => 2,
                    'name' => 'Paragliding',
                    'slug' => 'paragliding',
                    'short_description' => 'Tandem flying experience with mountain views.',
                    'full_description' => 'Fly over valleys with experienced pilots and HD video add-on options.',
                    'category' => 'Air',
                    'location' => 'Manali',
                    'destination' => 'Manali',
                    'price_min' => 1800,
                    'price_max' => 4500,
                    'price_type' => 'Per Person',
                    'duration' => '45 Minutes',
                    'difficulty' => 'Easy',
                    'status' => 'Active',
                    'featured' => true,
                    'packages_linked' => ['Manali Thrill Pack'],
                    'image' => 'https://images.unsplash.com/photo-1523867574998-7101fb6ddf4f?auto=format&fit=crop&w=1200&q=80',
                    'gallery' => [],
                    'tags' => ['Aerial', 'Photography'],
                    'age_limit' => '12+',
                    'best_time' => 'Oct to May',
                    'safety_instructions' => 'Weather dependent. Helmet and harness check required.',
                    'included' => 'Pilot, gear, briefing',
                    'excluded' => 'Action camera footage',
                    'seo_title' => 'Paragliding in Manali',
                    'meta_description' => 'Scenic tandem paragliding for mountain holidays.',
                    'keywords' => 'paragliding,manali,air activity',
                ],
                [
                    'id' => 3,
                    'name' => 'Jungle Safari',
                    'slug' => 'jungle-safari',
                    'short_description' => 'Guided wildlife safari with naturalist.',
                    'full_description' => 'Explore dense forest routes with trained drivers and tracking experts.',
                    'category' => 'Wildlife',
                    'location' => 'Ranthambore',
                    'destination' => 'Ranthambore',
                    'price_min' => 1500,
                    'price_max' => 4200,
                    'price_type' => 'Per Group',
                    'duration' => 'Half Day',
                    'difficulty' => 'Easy',
                    'status' => 'Draft',
                    'featured' => false,
                    'packages_linked' => ['Ranthambore Wildlife Retreat', 'Tiger Trail Journey'],
                    'image' => 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
                    'gallery' => [],
                    'tags' => ['Wildlife', 'Family'],
                    'age_limit' => '5+',
                    'best_time' => 'Nov to Apr',
                    'safety_instructions' => 'Stay seated in vehicle. No loud noises.',
                    'included' => 'Permit, guide, safari jeep',
                    'excluded' => 'Camera fee',
                    'seo_title' => 'Wildlife Safari Activity',
                    'meta_description' => 'Guided safari adventures for nature enthusiasts.',
                    'keywords' => 'safari,wildlife,ranthambore',
                ],
            ],
            'categories' => ['Adventure', 'Water', 'Air', 'Wildlife', 'Snow', 'Nature'],
            'difficulties' => ['Easy', 'Moderate', 'Hard'],
            'destinations' => ['Rishikesh', 'Manali', 'Goa', 'Ranthambore', 'Kashmir'],
            'tagOptions' => ['Water Sports', 'Aerial', 'Group', 'Family', 'Photography', 'Snow', 'Trekking', 'Camping'],
            'packageOptions' => [
                'Rishikesh Adventure Blast',
                'Weekend River Escape',
                'Manali Thrill Pack',
                'Goa Water Rush',
                'Kashmir Snow Escape',
                'Ranthambore Wildlife Retreat',
                'Tiger Trail Journey',
            ],
        ]);
    }
}
